part1: part1.c
	@gcc part1.c -o a.out
	@./a.out input.ppm output_part1.ppm
	@rm a.out

part2_1a: part2_1a.c
	@gcc part2_1a.c -o a.out -lpthread 
	@./a.out input.ppm output_part2_1a.ppm
	@rm a.out

part2_1b: part2_1b.c
	@gcc part2_1b.c -lpthread -o a.out
	@./a.out input.ppm output_part2_1b.ppm
	@rm a.out

part2_2: part2_2.c
	@gcc part2_2.c -lpthread -o a.out
	@./a.out input.ppm output_part2_2.ppm
	@rm a.out

part2_3: part2_3.c
	@gcc part2_3.c -lpthread
	@./a.out input.ppm output_part2_3.ppm
	@rm a.out

