CC=clang
#cflags for c compiler
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c11
#

all: half square twice

half: half.c
	$(CC) $(CFLAGS) half.c -o half

square: square.c
	$(CC) $(CFLAGS) square.c -o square

twice: twice.c
	$(CC) $(CFLAGS) twice.c -o twice